### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by plechi** [worldline/openshift-cartridge-tomcat#1]
I have installed the dependencies (tomcat6+7, jdk) but when i try to make a cartridge following error occurs:

Starting tomcat cartridge
Timed out waiting for http listening port
Failed to execute: 'control start' for /var/lib/openshift/<<id>>/tomcat

Do you have any idea how to fix this?

**Comment by Filirom1** [comment]
I tried on OpenShift online it worked : http://bcgbfgb-youpihoura.rhcloud.com/

If you are doing it on your own OpenShift instance, check the folder /opt/apache-tomcat-7.0 (or 6.0)

You can also take a look at /var/lib/openshift/<>/tomcat/logs dir

**Comment by plechi** [comment]
I found the error.
OPENSHIFT_GEAR_MEMORY_MB
is set to 0, so -Xmx is set to 0m.

Unfortunately I have not found any documentation, where OPENSHIFT_GEAR_MEMORY_MB can be modified.

**Comment by Filirom1** [comment]
Check that your cgroups are working.
This env. var was added by https://github.com/openshift/origin-server/pull/3828/files
